// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiqltgqxrfcgspedlbtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcWx0Z3F4cmZjZ3NwZWRsYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjU4NzIsImV4cCI6MjA2MTI0MTg3Mn0.gbonzfBroStZYwjzPMpQ8UYVs8Ky-2CwOdi4k8O-WlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);